"""Content Forensics — detect AI-generated text in reviews and dispute narratives.

Pipeline:
    1. Signals per text (interpretable, no black-box first):
         burstiness (sentence-length coefficient of variation), lexical
         diversity (TTR + moving-average TTR), textstat readability,
         punctuation/caps/exclamation rates, first-person rate, and TF-IDF
         template-reuse similarity against TRAIN flagged texts only.
    2. Three detectors, reported separately:
         - rule threshold on burstiness + readability (transparent baseline)
         - logistic regression on the full signal vector
         - Claude zero-shot judgment with reasons (the reasoning layer)
    3. Flagged texts become Case objects with evidence + reasoning_text,
       appended to the SQLite audit log.

Methodological notes (documented in the metrics JSON):
    - The held-out split is GROUP-BASED for AI texts: held-out topics were
      never used in training, so template-reuse must generalize rather than
      memorize our own generation phrasing.
    - AI texts were generated by different model families (minimax/gemma via
      OpenRouter free tier) than the detector (Claude), avoiding
      self-recognition bias.
    - Length band matched between classes so length is not a giveaway.

Usage:
    .venv/bin/python -m agents.content_forensics [--limit-llm N]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

import textstat
from eval.cost_table import decide
from eval.metrics import binary_metrics, format_report, pr_auc
from spine.db import DEFAULT_DB_PATH, connect, count_cases, insert_cases
from spine.llm import chat_json
from spine.schema import Case, Evidence

ROOT = Path(__file__).resolve().parents[1]
DATASET_PATH = ROOT / "data" / "processed" / "content_forensics_labeled.csv"
RESULTS_DIR = ROOT / "eval" / "results"

HELDOUT_GROUP_FRACTION = 0.30

RULES: dict[str, dict] = {
    "low_burstiness": {
        "weight": 0.30,
        "desc": "sentence-length variance below the human floor (uniform, machine-like rhythm)",
    },
    "high_readability": {
        "weight": 0.20,
        "desc": "readability grade above the human ceiling (polished, textbook phrasing)",
    },
    "template_reuse": {
        "weight": 0.30,
        "desc": "TF-IDF similarity to known AI-generated texts above the reuse threshold",
    },
    "low_lexical_diversity": {
        "weight": 0.20,
        "desc": "vocabulary repetition above the human ceiling",
    },
}


# ---------------------------------------------------------------------------
# Signals
# ---------------------------------------------------------------------------

def split_sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]


def compute_signals(text: str) -> dict:
    """Interpretable AI-text signals for one document."""
    words = re.findall(r"[A-Za-z']+", text.lower())
    sentences = split_sentences(text)
    n_words = max(len(words), 1)
    n_sent = max(len(sentences), 1)

    slens = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences] or [n_words]
    mean_sl = float(np.mean(slens))
    std_sl = float(np.std(slens))
    burstiness = std_sl / mean_sl if mean_sl > 0 else 0.0    # CV of sentence length

    # Moving-average type-token ratio (length-robust lexical diversity).
    window = 40
    ratios = []
    for i in range(max(len(words) - window + 1, 1)):
        chunk = words[i : i + window]
        if chunk:                      # empty text has no windows to average
            ratios.append(len(set(chunk)) / len(chunk))
    mattr = float(np.mean(ratios)) if ratios else 0.0

    first_person = sum(1 for w in words if w in ("i", "i'm", "me", "my", "mine"))
    return {
        "n_sentences": n_sent,
        "mean_sentence_len": mean_sl,
        "burstiness": burstiness,
        "mattr": mattr,                                   # lexical diversity
        "flesch_reading_ease": textstat.flesch_reading_ease(text),
        "flesch_kincaid_grade": textstat.flesch_kincaid_grade(text),
        "exclamation_rate": text.count("!") / n_sent,
        "caps_ratio": sum(1 for c in text if c.isupper()) / max(len(text), 1),
        "first_person_rate": first_person / n_words,
        "avg_word_len": sum(len(w) for w in words) / n_words,
        "text_len": len(text),
    }


SIGNAL_COLS = [
    "burstiness", "mattr", "flesch_reading_ease", "flesch_kincaid_grade",
    "exclamation_rate", "caps_ratio", "first_person_rate", "avg_word_len",
    "mean_sentence_len", "n_sentences",
]


class TemplateReuse:
    """Max TF-IDF similarity to TRAIN flagged texts — fitted on train only.

    Self-match matters here. The train AI texts ARE the reference matrix, so
    scoring one of them naively returns 1.0 (it matches itself), every train
    AI text scores 1.0, and any threshold derived from that distribution is
    unreachable by a held-out text — the rule then never fires. Training rows
    must therefore be scored with their own column masked out.
    """

    def __init__(self) -> None:
        self.vec = TfidfVectorizer(ngram_range=(1, 2), sublinear_tf=True,
                                   min_df=2, max_features=8000)
        self.train_ai_matrix = None
        self._row_of: dict[str, int] = {}

    def fit(self, train_ai_texts: list[str]) -> "TemplateReuse":
        try:
            self.train_ai_matrix = self.vec.fit_transform(train_ai_texts)
        except ValueError:
            # min_df=2 prunes every term when the corpus is tiny or shares no
            # vocabulary. Fall back rather than take down the whole agent.
            self.vec = TfidfVectorizer(ngram_range=(1, 2), sublinear_tf=True,
                                       min_df=1, max_features=8000)
            self.train_ai_matrix = self.vec.fit_transform(train_ai_texts)
        self._row_of = {t: i for i, t in enumerate(train_ai_texts)}
        return self

    def score_many(self, texts: list[str], exclude_self: bool = False) -> np.ndarray:
        if self.train_ai_matrix is None or self.train_ai_matrix.shape[0] == 0:
            return np.zeros(len(texts))
        sims = cosine_similarity(self.vec.transform(texts), self.train_ai_matrix)
        if exclude_self:
            for i, text in enumerate(texts):
                row = self._row_of.get(text)
                if row is not None:
                    sims[i, row] = -1.0
        return sims.max(axis=1).clip(min=0.0)

    def score(self, text: str) -> float:
        return float(self.score_many([text])[0])


# ---------------------------------------------------------------------------
# LLM zero-shot detector + reasoning
# ---------------------------------------------------------------------------

LLM_SYSTEM_PROMPT = (
    "You are a forensic analyst for a payments company. Decide whether a piece "
    "of user-submitted text (product review or dispute narrative) was written "
    "by a human or generated by an AI/LLM. Base your judgment on textual "
    "forensics only: rhythm uniformity (low sentence-length variance), "
    "overly polished or generic phrasing, template-like structure, unnatural "
    "consistency of tone, absence of typos/idioms, and vocabulary repetition. "
    "Be cautious: short casual texts can go either way. Respond with JSON "
    'only: {"verdict": "ai" | "human", "confidence": 0-1, "reasons": ["...", "..."]}'
)

DETECTOR_MODEL = "anthropic/claude-haiku-4.5"


def llm_classify(text: str, domain: str) -> dict:
    prompt = f"Text type: {domain} narrative.\n\nText:\n{text}\n\nJSON verdict:"
    out = chat_json(
        [{"role": "system", "content": LLM_SYSTEM_PROMPT},
         {"role": "user", "content": prompt}],
        model=DETECTOR_MODEL, temperature=0.0, max_tokens=300,
    )
    verdict = out.get("verdict", "human")
    if verdict not in ("ai", "human"):
        verdict = "human"
    return {
        "pred_ai": int(verdict == "ai"),
        "confidence": float(out.get("confidence", 0.5)),
        "reasons": list(out.get("reasons", []))[:4],
    }


# ---------------------------------------------------------------------------
# Case construction
# ---------------------------------------------------------------------------

def make_case(row: pd.Series, sig: dict, llm: dict | None,
              fallback_confidence: float = 0.5) -> Case:
    evidence = []
    if llm:
        for i, reason in enumerate(llm["reasons"]):
            evidence.append(Evidence(
                f"llm_reason_{i+1}", reason,
                round(0.20 * llm["confidence"] / max(len(llm["reasons"]), 1), 4)))
    if sig["burstiness"] < 0.35:
        evidence.append(Evidence(
            "low_burstiness",
            f"sentence-length variance {sig['burstiness']:.2f} "
            f"(humans typically > 0.35)",
            RULES["low_burstiness"]["weight"]))
    if sig["flesch_kincaid_grade"] > 14:
        evidence.append(Evidence(
            "high_readability",
            f"Flesch-Kincaid grade {sig['flesch_kincaid_grade']:.1f} "
            f"(human reviews typically < 14)",
            RULES["high_readability"]["weight"]))
    if "template_reuse_score" in row and row["template_reuse_score"] > 0.35:
        evidence.append(Evidence(
            "template_reuse",
            f"TF-IDF similarity {row['template_reuse_score']:.2f} to known "
            f"AI-generated texts",
            RULES["template_reuse"]["weight"]))
    if sig["mattr"] < 0.55:
        evidence.append(Evidence(
            "low_lexical_diversity",
            f"lexical diversity (MATTR) {sig['mattr']:.2f} below human floor",
            RULES["low_lexical_diversity"]["weight"]))

    domain_label = "product review" if row["domain"] == "review" else "dispute narrative"
    conf = llm["confidence"] if llm else fallback_confidence
    # Content Forensics never auto-blocks: FN:FP is 2.33, below the policy
    # bar, because wrongly denying a real customer's dispute is close in cost
    # to paying out a fake one — and far worse for the customer.
    has_evidence = any(e.signal in RULES for e in evidence)
    decision, policy_why = decide("content_forensics", conf, has_evidence)
    reasoning = "; ".join(llm["reasons"]) if llm else "signal-based flag"
    return Case(
        source_agent="content_forensics",
        entity_id=str(row["prompt_group"]),
        entity_type="dispute" if row["domain"] == "dispute" else "document",
        evidence=evidence,
        confidence=conf,
        cost_estimate=25.0,   # proxy: wrongly denying a genuine customer text
        decision=decision,
        reasoning_text=(
            f"Flagged {domain_label} as likely AI-generated "
            f"(confidence {conf:.2f}). Forensic reasoning: {reasoning}. "
            f"Signals: burstiness={sig['burstiness']:.2f}, "
            f"readability grade={sig['flesch_kincaid_grade']:.1f}, "
            f"lexical diversity={sig['mattr']:.2f}. "
            f"Action `{decision}`: {policy_why}."
        ),
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--limit-llm", type=int, default=0,
                    help="cap LLM-detector calls (smoke runs); 0 = all")
    ap.add_argument("--no-llm", action="store_true",
                    help="skip the LLM detector entirely (no API spend); the "
                         "rule and logistic-regression detectors still run")
    ap.add_argument("--max-cases", type=int, default=1000,
                    help="cap on cases written to the audit log this run")
    return ap.parse_args()


def _stable_hash(value: str) -> int:
    """Deterministic, uniformly distributed hash (Python's hash() is salted)."""
    return int(hashlib.md5(str(value).encode()).hexdigest()[:8], 16)


def group_split(df: pd.DataFrame) -> pd.DataFrame:
    """Assign train/heldout by prompt group, stratified by domain AND class.

    AI rows share one group id per topic, so held-out AI texts come from
    topics never seen in training and the template-reuse signal has to
    generalize instead of memorizing our own generation phrasing. Human rows
    carry unique corpus ids, so the same rule gives them a random row split.

    Two things this must not get wrong, both of which it previously did:
      - A naive `sum(ord(c)) % 100` hash is nearly constant across strings
        that share a prefix. Every AI group ("dispute_topic00"...) collided
        into one end of the range and every human corpus id into the other,
        so the split lined up exactly with the label: held-out ended up
        100% AI, no negatives, and precision was trivially 1.0.
      - Even with a good hash, per-group Bernoulli draws can leave a class
        or a domain badly under-represented at this sample size.
    Selecting a fixed fraction of groups by hash RANK within each
    (domain, class) stratum removes both failure modes and stays
    deterministic across runs.
    """
    df = df.copy()
    df["split"] = "train"
    for (domain, is_ai), block in df.groupby(["domain", "is_ai_generated"]):
        groups = sorted(block["prompt_group"].astype(str).unique(),
                        key=_stable_hash)
        n_held = max(1, round(len(groups) * HELDOUT_GROUP_FRACTION))
        held = set(groups[:n_held])
        mask = (df["domain"] == domain) & (df["is_ai_generated"] == is_ai) & \
               df["prompt_group"].astype(str).isin(held)
        df.loc[mask, "split"] = "heldout"
    return df


def main() -> None:
    args = parse_args()

    df = pd.read_csv(DATASET_PATH)
    df = group_split(df)
    train = df[df["split"] == "train"].copy()
    held = df[df["split"] == "heldout"].copy()
    for dom in ("review", "dispute"):
        t, h = train[train["domain"] == dom], held[held["domain"] == dom]
        print(f"{dom:<8} train: {len(t):>4} "
              f"(AI {int((t['is_ai_generated']==1).sum())})   "
              f"heldout: {len(h):>4} (AI {int((h['is_ai_generated']==1).sum())})")

    # --- signals ------------------------------------------------------------
    t0 = time.perf_counter()
    sig_train = pd.DataFrame([compute_signals(t) for t in train["text"]],
                             index=train.index)
    sig_held = pd.DataFrame([compute_signals(t) for t in held["text"]],
                            index=held.index)
    reuse = TemplateReuse().fit(
        train.loc[train["is_ai_generated"] == 1, "text"].tolist())
    # Train rows are scored with their own column masked (see TemplateReuse);
    # held-out rows are not in the reference matrix, so no masking is needed.
    train["template_reuse_score"] = reuse.score_many(
        train["text"].tolist(), exclude_self=True)
    held["template_reuse_score"] = reuse.score_many(held["text"].tolist())
    signal_time = time.perf_counter() - t0

    # --- detector 1: rule threshold (tuned on train only) --------------------
    burst_floor = float(np.quantile(sig_train.loc[train["is_ai_generated"] == 0,
                                                   "burstiness"], 0.10))
    grade_ceil = float(np.quantile(sig_train.loc[train["is_ai_generated"] == 0,
                                                 "flesch_kincaid_grade"], 0.90))
    reuse_thr = float(np.quantile(train.loc[train["is_ai_generated"] == 1,
                                             "template_reuse_score"], 0.25))
    print(f"\nRule thresholds (train): burstiness floor {burst_floor:.2f}, "
          f"grade ceiling {grade_ceil:.1f}, reuse threshold {reuse_thr:.2f}")

    rule_pred = (
        (sig_held["burstiness"] < burst_floor).astype(int)
        | (sig_held["flesch_kincaid_grade"] > grade_ceil).astype(int)
        | (held["template_reuse_score"] > reuse_thr).astype(int)
    )

    # --- detector 2: logistic regression on signals --------------------------
    X_train = pd.concat([sig_train[SIGNAL_COLS],
                         train["template_reuse_score"].rename("template_reuse_score")],
                        axis=1)
    X_held = pd.concat([sig_held[SIGNAL_COLS],
                        held["template_reuse_score"].rename("template_reuse_score")],
                       axis=1)
    # Scaling is not optional here: these signals span three orders of
    # magnitude (caps_ratio ~0.01 vs flesch_reading_ease ~0-100). Unscaled,
    # the solver collapsed to predicting the majority class for every row.
    lr = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, C=1.0))
    lr.fit(X_train, train["is_ai_generated"])
    lr_score = lr.predict_proba(X_held)[:, 1]
    lr_pred = (lr_score >= 0.5).astype(int)

    # --- detector 3: LLM zero-shot + reasoning -------------------------------
    llm_start = 0 if args.no_llm else min(len(held), args.limit_llm or len(held))
    t0 = time.perf_counter()
    llm_out: dict[int, dict] = {}
    for i, (idx, row) in enumerate(held.head(llm_start).iterrows()):
        llm_out[idx] = llm_classify(row["text"], row["domain"])
        if (i + 1) % 25 == 0:
            print(f"  LLM detector {i+1}/{llm_start}")
    llm_time = time.perf_counter() - t0
    llm_eval = held.head(llm_start)
    llm_pred = np.array([llm_out[i]["pred_ai"] for i in llm_eval.index])
    llm_conf = np.array([llm_out[i]["confidence"] for i in llm_eval.index])
    if llm_start:
        print(f"  LLM detector evaluated on {llm_start} of {len(held)} "
              f"held-out texts")

    # --- report ---------------------------------------------------------------
    results = {
        "rule_threshold": binary_metrics(held["is_ai_generated"], rule_pred),
        "logistic_regression": {
            **binary_metrics(held["is_ai_generated"], lr_pred),
            "pr_auc": pr_auc(held["is_ai_generated"], lr_score),
        },
    }
    if llm_start:
        y_llm = llm_eval["is_ai_generated"]
        results["llm_zeroshot"] = {
            **binary_metrics(y_llm, llm_pred),
            "mean_confidence": round(float(llm_conf.mean()), 3),
            "n_evaluated": int(llm_start),
            "n_heldout_total": int(len(held)),
        }
    else:
        print("\nLLM detector SKIPPED (--no-llm): rule and logistic-regression "
              "detectors below are complete; the reasoning layer is not "
              "evaluated in this run.")
    for name, m in results.items():
        print(format_report(f"[held-out] {name}", m))
    print(f"\nSignal extraction: {signal_time/max(len(df),1)*1000:.1f} ms/text; "
          f"LLM detector: {llm_time/max(llm_start,1):.2f} s/text "
          f"({llm_start} calls, disk-cached on re-runs)")

    # signal quality: standardized mean gap between classes per signal
    ai_mask = held["is_ai_generated"] == 1
    sep = {}
    for col in SIGNAL_COLS:
        a, b = sig_held.loc[ai_mask, col], sig_held.loc[~ai_mask, col]
        sd = pd.concat([a, b]).std() or 1.0
        sep[col] = round(float((a.mean() - b.mean()) / sd), 3)
    a = held.loc[ai_mask, "template_reuse_score"]
    b = held.loc[~ai_mask, "template_reuse_score"]
    sd = pd.concat([a, b]).std() or 1.0
    sep["template_reuse_score"] = round(float((a.mean() - b.mean()) / sd), 3)
    print(f"\nSignal separation (|effect| > 0.5 meaningful): {sep}")

    # --- cases for flagged held-out texts --------------------------------------
    # Which detector supplies the flags depends on what ran: the LLM when it
    # was called, otherwise the logistic-regression detector. Either way the
    # audit log gets populated — case files are not an LLM-only feature.
    if llm_start:
        flagged_idx = [i for i in llm_eval.index if llm_out[i]["pred_ai"] == 1]
        flag_source = "llm_zeroshot"
    else:
        flagged_idx = [i for i, pred in zip(held.index, lr_pred) if pred == 1]
        flag_source = "logistic_regression"
    cases = []
    for idx in flagged_idx[: args.max_cases]:
        row = held.loc[idx]
        sig = sig_held.loc[idx].to_dict()
        conf = float(lr_score[held.index.get_loc(idx)])
        cases.append(make_case(row, sig, llm_out.get(idx), conf))
    conn = connect(DEFAULT_DB_PATH)
    insert_cases(conn, cases)
    print(f"\nFlags for case files came from: {flag_source}")
    print(f"Wrote {len(cases)} content_forensics cases; audit log now holds "
          f"{count_cases(conn, 'content_forensics')} content_forensics / "
          f"{count_cases(conn)} total")

    # --- save ------------------------------------------------------------------
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    report = {
        "agent": "content_forensics",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "dataset": {
            "n_total": len(df), "n_train": len(train), "n_heldout": len(held),
            "heldout_fraction_groups": HELDOUT_GROUP_FRACTION,
            "split": "group-based for AI (unseen topics), hashed-id for human",
            "generator_models": sorted(
                df.loc[df["is_ai_generated"] == 1, "source"].unique().tolist()),
            "detector_model": DETECTOR_MODEL,
            "caveats": [
                "AI texts generated by minimax/gemma; detector is Claude — "
                "different families, so no self-recognition advantage, but "
                "both are 2026-era LLMs",
                "human reviews from Amazon corpus, disputes from CFPB "
                "complaints (US finance domain); KYC self-descriptions "
                "out of eval scope (no public genuine-human corpus)",
            ],
        },
        "results": results,
        "rule_thresholds": {
            "burstiness_floor": round(burst_floor, 3),
            "fk_grade_ceiling": round(grade_ceil, 2),
            "template_reuse_threshold": round(reuse_thr, 3),
        },
        "signal_separation_heldout": sep,
        "timing": {
            "signal_ms_per_text": round(signal_time / max(len(df), 1) * 1000, 1),
            "llm_s_per_text": round(llm_time / max(llm_start, 1), 2),
        },
        "cases_written": len(cases),
        "case_flag_source": flag_source,
        "lr_coefficients": {
            c: round(float(v), 3)
            for c, v in zip(X_train.columns,
                            lr.named_steps["logisticregression"].coef_[0])
        },
    }
    out_path = RESULTS_DIR / "content_forensics_metrics.json"
    with open(out_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"Saved metrics to {out_path}")


if __name__ == "__main__":
    main()
